### ISSUE TITLE
image processing using cuda

### ISSUE THREAD

**Issue by hellypatel92** [madsravn/madsravn.github.io#4]
can you suggest me about  programming  in image processing using Cuda in java by using JCuda ??

**Comment by madsravn** [comment]
Hello hellypatel92,

I don't have any experience doing Cuda with java. Why not just use this small example I have here, and do it with C++? I'm certain there are more resources on Cuda with C++ than with Java.

**Comment by hellypatel92** [comment]
Hello Mads Ravn,

  Thanks for your instant reply.Can u pl suggest me someone who is able to
do this thing or can help me??? I also want to ask you that do you know
about image processing using hadoop??
Thanks and waiting for your reply.
Have a nice day.

**Comment by madsravn** [comment]
I haven't done any CUDA programming in JAVA. I don't really know how it differs. And I don't really know anyone who does it. You can try coming to the #cuda irc channel on irc.freenode.net and ask.

For hadoop, you can just google. There are lots of tutorials and libraries for that.

Best regards

**Comment by hellypatel92** [comment]
Thanks a lot.
